services:
  - type: web
    name: studymate-app
    plan: free
    runtime: docker
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.vfhswjfjwqjmpcxjgedc
      - key: SPRING_DATASOURCE_PASSWORD
        value: ahtasham2105067
      - key: JWT_SECRET
        value: studymate-free-jwt-secret-key-2024
      - key: JWT_EXPIRATION
        value: 86400000
      - key: GEMINI_API_KEY
        value: AIzaSyA2DsN6bTwwuySdLO-VkPwuaKBW19ShbSk
      - key: GEMINI_API_URL
        value: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: FILE_UPLOAD_DIR
        value: /tmp/uploads
      - key: MAX_FILE_SIZE
        value: 10MB
      - key: MAX_REQUEST_SIZE
        value: 10MB
